language: node_js
node_js:
  - "0.10"
notifications:
  email: false
deploy:
  provider: heroku
  app: fortena
  api_key:
    secure: iPPYeMiQ1IUuLW4V8CzaiA
before_deploy:
  if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
